-- Run this in Supabase SQL Editor.

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  service text not null,
  preferred_date date not null,
  preferred_time text not null,
  pet_name text not null,
  breed text not null,
  notes text,
  owner_name text not null,
  phone text not null,
  status text not null default 'pending',
  private_quote text,
  admin_notes text
);

alter table public.bookings enable row level security;

create policy "Allow public booking requests"
on public.bookings
for insert
to anon
with check (status = 'pending');

create table if not exists public.availability (
  id bigint generated by default as identity primary key,
  day_of_week integer check (day_of_week between 0 and 6),
  time_label text not null,
  active boolean not null default true,
  unique(day_of_week, time_label)
);

insert into public.availability (day_of_week, time_label)
values
  (1,'5:30 PM'),(1,'6:30 PM'),
  (2,'5:30 PM'),(2,'6:30 PM'),
  (3,'5:30 PM'),(3,'6:30 PM'),
  (4,'5:30 PM'),(4,'6:30 PM'),
  (5,'5:30 PM'),(5,'6:30 PM'),
  (6,'1:00 PM'),(6,'3:00 PM'),(6,'6:00 PM')
on conflict do nothing;

alter table public.availability enable row level security;

create policy "Public can read active availability"
on public.availability
for select
to anon
using (active = true);
